Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,56 +1,89 @@
-# .github/workflows/rspec.yml
-name: tests
-on: push
-
+# This workflow uses actions that are not certified by GitHub.  They are
+# provided by a third-party and are governed by separate terms of service,
+# privacy policy, and support documentation.
+#
+# This workflow will install a prebuilt Ruby version, install dependencies, and
+# run tests and linters.
+name: "Ruby on Rails CI"
+on:
+  push:
+    branches: [ "main" ]
+  pull_request:
+    branches: [ "main" ]
 jobs:
-  build:
-    name: rspec
+  test:
     runs-on: ubuntu-latest
-
     services:
-      postgres:
-        image: postgres
+      db:
+        image: postgres:15.2
         env:
+          POSTGRES_HOST: 127.0.0.1
+          POSTGRES_DB: auth
           POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: postgres
-          POSTGRES_DB: postgres
+          POSTGRES_PASSWORD: password
         ports:
           - 5432:5432
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-      redis:
-        image: redis
-        ports:
-          - 6379:6379
+        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
+
+    container:
+      image: ivankhoda/auth-app:latest
+      credentials:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
 
     steps:
-      - uses: actions/checkout@v2
-      - uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: 3.0.0
-      - name: Install PostgreSQL
-        run: sudo apt-get -yqq install libpq-dev
-      - name: Run bundle install
-        run: |
-          gem install bundler
-          bundle install --jobs 4 --retry 3
-      - name: Setup Database
-        env:
-          RAILS_ENV: test
-          POSTGRES_HOST: localhost
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: postgres
-          POSTGRES_DB: postgres
-        run: bin/rails db:create db:schema:load
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-      - name: Build and test with rspec
-        env:
-          RAILS_ENV: test
-          POSTGRES_HOST: localhost
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: postgres
-          POSTGRES_DB: postgres
-        run: bundle exec rspec
+      - name: install PostgreSQL client
+        run: sudo apt-get install libpq-dev
+
+#       - name: Build and create DB
+#         env:
+#           POSTGRES_HOST: 127.0.0.1
+#           POSTGRES_USER: postgres
+#           POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
+#           POSTGRES_PASSWORD: password
+#           RAILS_ENV: test
+#         run: |
+#           gem install bundler
+#           bundle install --jobs 4 --retry 3
+#           bin/rails db:setup
+
+#       - name: run bundle install
+#         run: bundle install --jobs=8 --path vendor/bundle
+
+#       - name: Create DB
+#         run: |
+#           RAILS_ENV=test bundle exec rake parallel:create
+
+
+#       - name: Run load from schema
+#         run: RAILS_ENV=test bundle exec rake parallel:rake[db:schema:load]
+
+#       - name: Run migrate DB
+#         run: RAILS_ENV=test bundle exec rake parallel:migrate
+
+#       - name: Run create tmp DB
+#         run: RAILS_ENV=test bundle exec rake tmp:create
+
+#       - name: Run Rubocop
+#         run: bundle exec rubocop -c .rubocopignorebuild.yml
+
+#       - name: Run rspec
+#         run: COVERAGE=true RAILS_ENV=test bundle exec parallel_rspec ./spec
+
+#       - name: Stash Coverage Results
+#         run: |
+#           mkdir coverage_results
+#           cp -R coverage/.resultset.json coverage_results/.resultset-0.json
+
+#       - name: Run report_coverage
+#         run: RAILS_ENV=test bundle exec rake simplecov:report_coverage
+
+#       - name: Save coverage
+#         uses: actions/upload-artifact@v3
+#         if: success() || failure()
+#         with:
+#           name: coverage
+#           path: ./coverage
